language: go

go:
  - 1.8
  - 1.9
  - "1.10.1"

before_install:
  - go get -t -v ./...
  - go get -v github.com/mattn/goveralls
  - go get -v golang.org/x/tools/cmd/cover

script:
  - go test -coverprofile=coverage.txt
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.txt -v -service=travis-ci