// DO NOT EDIT.
// GENERATED by go:generate at 2019-05-20 13:26:16.572135 +0000 UTC.
package gounity

// AffectedResource defines `affectedResource` type.
type AffectedResource struct {
	Resource

	Id   string `json:"id"`
	Name string `json:"name"`
}
