// DO NOT EDIT.
// GENERATED by go:generate at 2019-06-05 15:12:15.985747 +0000 UTC.
package gounity

// AffectedResource defines `affectedResource` type.
type AffectedResource struct {
	Resource

	Id   string `json:"id"`
	Name string `json:"name"`
}
