// DO NOT EDIT.
// GENERATED by go:generate at 2019-05-15 06:25:01.187215664 +0000 UTC.
package gounity

// BlockHostAccess defines `blockHostAccess` type.
type BlockHostAccess struct {
	Resource

	Host       *Host             `json:"host"`
	AccessMask HostLUNAccessEnum `json:"accessMask"`
}
