// DO NOT EDIT.
// GENERATED by go:generate at 2019-05-17 11:31:28.023478 +0000 UTC.
package gounity

// BlockHostAccess defines `blockHostAccess` type.
type BlockHostAccess struct {
	Resource

	Host       *Host             `json:"host"`
	AccessMask HostLUNAccessEnum `json:"accessMask"`
}
