// DO NOT EDIT.
// GENERATED by go:generate at 2018-12-31 08:45:04.777328006 +0000 UTC.
package gounity

type BlockHostAccessEnum int

const (

	// BlockHostAccessOff means: Access is disabled.
	BlockHostAccessOff BlockHostAccessEnum = 0

	// BlockHostAccessOn means: Access is enabled.
	BlockHostAccessOn BlockHostAccessEnum = 1

	// BlockHostAccessMixed means: (Applies to Consistency Groups only.) Indicates that LUNs in a consistency group have different host access.
	BlockHostAccessMixed BlockHostAccessEnum = 2
)

type FSSupportedProtocolEnum int

const (

	// FSSupportedProtocolNFS means: Only NFS share protocol supported by file system.
	FSSupportedProtocolNFS FSSupportedProtocolEnum = 0

	// FSSupportedProtocolCIFS means: Only SMB (also known as CIFS) share protocol is supported by file system.
	FSSupportedProtocolCIFS FSSupportedProtocolEnum = 1

	// FSSupportedProtocolMultiprotocol means: Both share protocols NFS and SMB (also known as CIFS) are supported by file system.
	FSSupportedProtocolMultiprotocol FSSupportedProtocolEnum = 2
)

type HostLUNAccessEnum int

const (

	// HostLUNAccessNoAccess means: No access.
	HostLUNAccessNoAccess HostLUNAccessEnum = 0

	// HostLUNAccessProduction means: Access to production LUNs only.
	HostLUNAccessProduction HostLUNAccessEnum = 1

	// HostLUNAccessSnapshot means: Access to LUN snapshots only.
	HostLUNAccessSnapshot HostLUNAccessEnum = 2

	// HostLUNAccessBoth means: Access to both production LUNs and their snapshots.
	HostLUNAccessBoth HostLUNAccessEnum = 3

	// HostLUNAccessProductionOn means: Request to grant production access to LUNs for host. Should be used only by GUI.
	HostLUNAccessProductionOn HostLUNAccessEnum = 4

	// HostLUNAccessProductionOff means: Request to deny production access to LUNs for host. Should be used only by GUI.
	HostLUNAccessProductionOff HostLUNAccessEnum = 5

	// HostLUNAccessMixed means: (Applies to consistency groups only.) Indicates that LUNs in a consistency group have different host access. Do not use this value in Create or Modify requests.
	HostLUNAccessMixed HostLUNAccessEnum = 65535
)

type HostLunTypeEnum int

const (

	// HostLunTypeUnknown means: Unknown LUN type.
	HostLunTypeUnknown HostLunTypeEnum = 0

	// HostLunTypeLUN means: Production LUN.
	HostLunTypeLUN HostLunTypeEnum = 1

	// HostLunTypeLUN_Snap means: Snapshot LUN.
	HostLunTypeLUN_Snap HostLunTypeEnum = 2
)

type NFSShareDefaultAccessEnum int

const (

	// NFSShareDefaultAccessNoAccess means: Deny access to the share for the hosts.
	NFSShareDefaultAccessNoAccess NFSShareDefaultAccessEnum = 0

	// NFSShareDefaultAccessReadOnly means: Allow read only access to the share for the hosts.
	NFSShareDefaultAccessReadOnly NFSShareDefaultAccessEnum = 1

	// NFSShareDefaultAccessReadWrite means: Allow read write access to the share for the hosts.
	NFSShareDefaultAccessReadWrite NFSShareDefaultAccessEnum = 2

	// NFSShareDefaultAccessRoot means: Allow read write root access to the share for the hosts.
	NFSShareDefaultAccessRoot NFSShareDefaultAccessEnum = 3

	// NFSShareDefaultAccessRoRoot means: Allow read only root access to the share for the hosts.
	NFSShareDefaultAccessRoRoot NFSShareDefaultAccessEnum = 4
)
