// DO NOT EDIT.
// GENERATED by go:generate at 2019-06-05 15:12:15.984251 +0000 UTC.
package gounity

import (
	"github.com/pkg/errors"
)

const (

	// UnityLunNameExistErrorCode is error code of UnityLunNameExist.
	UnityLunNameExistErrorCode = 108007744

	// UnityResourceNotFoundErrorCode is error code of UnityResourceNotFound.
	UnityResourceNotFoundErrorCode = 131149829
)

// IsUnityLunNameExistError returns true or false on whether
// its error code is UnityLunNameExistErrorCode.
func IsUnityLunNameExistError(err error) bool {
	e, ok := errors.Cause(err).(*unityError)
	return ok && e.ErrorCode == UnityLunNameExistErrorCode
}

// IsUnityResourceNotFoundError returns true or false on whether
// its error code is UnityResourceNotFoundErrorCode.
func IsUnityResourceNotFoundError(err error) bool {
	e, ok := errors.Cause(err).(*unityError)
	return ok && e.ErrorCode == UnityResourceNotFoundErrorCode
}
