// THIS FILE IS GENERATED BY `go generate`. DO NOT MODIFY IT MANUALLY.
package gounity

import (
	"github.com/pkg/errors"
)

// IsUnityResourceNotFoundError returns true or false on whether the error is UnityResourceNotFoundError.
func IsUnityResourceNotFoundError(err error) bool {
	e, ok := errors.Cause(err).(*unityError)
	return ok && e.ErrorCode == UnityResourceNotFoundErrorCode
}

// IsUnityLunNameExistError returns true or false on whether the error is UnityLunNameExistError.
func IsUnityLunNameExistError(err error) bool {
	e, ok := errors.Cause(err).(*unityError)
	return ok && e.ErrorCode == UnityLunNameExistErrorCode
}
