#!/bin/bash

tmpl='
// IsUnityDUMMYError returns true or false on whether the error is UnityDUMMYError.
func IsUnityDUMMYError(err error) bool {
	e, ok := errors.Cause(err).(*unityError)
	return ok && e.ErrorCode == UnityDUMMYErrorCode
}'

errors=$(sed -n 's/Unity\(\w\+\)ErrorCode[\ \t]*=[\ \t][0-9]\+/\1/p' ./errors.go)

echo '// THIS FILE IS GENERATED BY `go generate`. DO NOT MODIFY IT MANUALLY.
package gounity

import (
	"github.com/pkg/errors"
)' > ./errors_gen.go

for e in ${errors}; do
    echo "${tmpl//DUMMY/${e}}" >> ./errors_gen.go
done