// DO NOT EDIT.
// GENERATED by go:generate at 2019-05-20 13:26:16.578874 +0000 UTC.
package gounity

// Health defines `health` type.
type Health struct {
	Resource

	Value          int      `json:"value"`
	DescriptionIds []string `json:"descriptionIds"`
	Descriptions   []string `json:"descriptions"`
}
