// DO NOT EDIT.
// GENERATED by go:generate at 2019-06-06 09:02:53.362711 +0000 UTC.
package gounity

// JobMessage defines `jobMessage` type.
type JobMessage struct {
	Resource

	ErrorCode      uint32              `json:"errorCode"`
	Created        string              `json:"created"`
	HttpStatusCode uint32              `json:"httpStatusCode"`
	Messages       []*LocalizedMessage `json:"messages"`
	MessageArgs    []string            `json:"messageArgs"`
}
