// DO NOT EDIT.
// GENERATED by go:generate at 2019-06-06 09:02:53.363917 +0000 UTC.
package gounity

// JobTaskRequest defines `jobTaskRequest` type.
type JobTaskRequest struct {
	Resource

	Name         string   `json:"name"`
	Description  string   `json:"description"`
	SubmitTime   string   `json:"submitTime"`
	StartTime    string   `json:"startTime"`
	Object       string   `json:"object"`
	Action       string   `json:"action"`
	Dependencies []string `json:"dependencies"`
}
