// DO NOT EDIT.
// GENERATED by go:generate at 2019-05-17 11:31:28.035498 +0000 UTC.
package gounity

// JobTask defines `jobTask` type.
type JobTask struct {
	Resource

	Name             string            `json:"name"`
	Description      string            `json:"description"`
	Object           string            `json:"object"`
	Action           string            `json:"action"`
	State            JobTaskStateEnum  `json:"state"`
	Messages         []string          `json:"messages"`
	Steps            []*JobTask        `json:"steps"`
	ParametersIn     string            `json:"parametersIn"`
	ParametersOut    string            `json:"parametersOut"`
	SubmitTime       string            `json:"submitTime"`
	StartTime        string            `json:"startTime"`
	AffectedResource *AffectedResource `json:"affectedResource"`
}
