// DO NOT EDIT.
// GENERATED by go:generate at 2019-06-06 09:02:53.364917 +0000 UTC.
package gounity

// JobTask defines `jobTask` type.
type JobTask struct {
	Resource

	Name             string            `json:"name"`
	Description      string            `json:"description"`
	Object           string            `json:"object"`
	Action           string            `json:"action"`
	State            JobTaskStateEnum  `json:"state"`
	Messages         []*JobMessage     `json:"messages"`
	Steps            []*JobTask        `json:"steps"`
	ParametersIn     string            `json:"parametersIn"`
	ParametersOut    string            `json:"parametersOut"`
	SubmitTime       string            `json:"submitTime"`
	StartTime        string            `json:"startTime"`
	AffectedResource *AffectedResource `json:"affectedResource"`
}
