// DO NOT EDIT.
// GENERATED by go:generate at 2019-06-05 15:12:16.003768 +0000 UTC.
package gounity

// LocalizedMessage defines `localizedMessage` type.
type LocalizedMessage struct {
	Resource

	Locale  string `json:"locale"`
	Message string `json:"message"`
}
