// DO NOT EDIT.
// GENERATED by go:generate at 2019-05-17 11:31:28.036709 +0000 UTC.
package gounity

// LocalizedMessage defines `localizedMessage` type.
type LocalizedMessage struct {
	Resource

	Locale  string `json:"locale"`
	Message string `json:"message"`
}
