// DO NOT EDIT.
// GENERATED by go:generate at 2019-06-13 09:18:08.230455701 +0000 UTC.
package gounity

// SnapHostAccess defines `snapHostAccess` type.
type SnapHostAccess struct {
	Resource

	Host       *Host               `json:"host"`
	AccessMask SnapAccessLevelEnum `json:"accessMask"`
}
