// DO NOT EDIT.
// GENERATED by go:generate at 2019-05-15 06:25:01.211020128 +0000 UTC.
package gounity

// SnapHostAccess defines `snapHostAccess` type.
type SnapHostAccess struct {
	Resource

	Host       *Host               `json:"host"`
	AccessMask SnapAccessLevelEnum `json:"accessMask"`
}
